version: "3.8"

services:
  shareboard:
    build: .
    container_name: shareboard_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL} # Pass these to shareboard too
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
